<a href="https://colab.research.google.com/github/hyona-yu/HAR_python/blob/master/har_with_uci_data_ver2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import random

In [2]:
from sklearn.metrics import classification_report

In [3]:
device ='cuda' if torch.cuda.is_available() else 'cpu'
random.seed(42)
torch.manual_seed(42)
if device =='cuda':
    torch.cuda.manual_seed_all(42)

In [4]:
! git clone https://github.com/hyona-yu/Dataset.git

Cloning into 'Dataset'...
remote: Enumerating objects: 660, done.
remote: Total 660 (delta 0), reused 0 (delta 0), pack-reused 660
Receiving objects: 100% (660/660), 427.85 MiB | 23.97 MiB/s, done.
Resolving deltas: 100% (140/140), done.
Checking out files: 100% (626/626), done.


In [5]:
url = 'Dataset/UCI HAR Dataset/'

In [6]:
#time step 128
signal = ['body_acc_x_', 'body_acc_y_','body_acc_z_','body_gyro_x_','body_gyro_y_','body_gyro_z_','total_acc_x_','total_acc_y_','total_acc_z_']

In [7]:
train_csv = pd.DataFrame()
for s in signal:
  train_path = str(url + "train/Inertial Signals/"+ s + "train.txt")
  train_csv = pd.concat([train_csv, pd.read_csv(train_path, sep ='\s+', header = None)], axis = 1)

In [8]:
train_csv

0         1         2    ...       125       126       127
0     0.000181  0.010139  0.009276  ...  0.100385  0.099874  0.094987
1     0.001094  0.004550  0.002879  ...  0.093535  0.089035  0.090612
2     0.003531  0.002285 -0.000420  ...  0.083011  0.082334  0.081487
3    -0.001772 -0.001311  0.000388  ...  0.085761  0.083275  0.081404
4     0.000087 -0.000272  0.001022  ...  0.081329  0.085397  0.088816
...        ...       ...       ...  ...       ...       ...       ...
7347  0.388873  0.618763  0.774067  ...  0.086288  0.099188  0.129060
7348  0.711864  0.709237  0.321368  ...  0.199324  0.236369  0.253029
7349 -0.226717 -0.177817 -0.150869  ...  0.111295  0.126302  0.188621
7350 -0.064806 -0.079933 -0.068350  ...  0.128925  0.172251  0.210071
7351 -0.194471 -0.173802 -0.127545  ... -0.156105 -0.122798 -0.083572

[7352 rows x 1152 columns]

In [9]:
test_csv = pd.DataFrame()
for s in signal:
  test_path = str(url + "test/Inertial Signals/"+ s + "test.txt")
  test_csv = pd.concat([test_csv, pd.read_csv(test_path, sep ='\s+', header = None)], axis = 1)

In [10]:
test_csv

0         1         2    ...       125       126       127
0     0.011653  0.013109  0.011269  ...  0.144395  0.144703  0.145494
1     0.009280  0.004930  0.003954  ...  0.152788  0.139843  0.121314
2     0.005732  0.007066  0.005110  ...  0.132678  0.132694  0.132117
3     0.000452  0.000604 -0.002485  ...  0.116060  0.110997  0.111912
4    -0.004362 -0.002765 -0.004905  ...  0.125895  0.122510  0.122760
...        ...       ...       ...  ...       ...       ...       ...
2942  0.107662  0.124079  0.183420  ... -0.330635 -0.254794 -0.229436
2943 -0.042392 -0.017244  0.015269  ... -0.355499 -0.500135 -0.489756
2944 -0.147647 -0.169903 -0.168698  ... -0.272397 -0.067734  0.137826
2945  0.071227 -0.088665 -0.070675  ... -0.003512 -0.111786 -0.276068
2946 -0.193642 -0.064987 -0.097122  ... -0.072539 -0.050975 -0.028925

[2947 rows x 1152 columns]

In [11]:
train_y = pd.read_csv(url + 'train/y_train.txt', header = None, names= ['label'])
test_y =pd.read_csv(url + 'test/y_test.txt', header =None, names= ['label'])

In [12]:
for i in range(len(train_y)):
  if train_y.loc[i,'label'] >=7 :
    train_csv.drop(i, inplace =True)
    train_y.drop(i, inplace = True)

In [13]:
for i in range(len(test_y)):
  if test_y.loc[i,'label'] >=7 :
    test_csv.drop(i, inplace =True)
    test_y.drop(i, inplace = True)

In [14]:
train_D = np.array(train_csv).reshape(train_csv.shape[0], 128, -1)

In [15]:
train_D.shape

(7352, 128, 9)

In [16]:
test_D = np.array(test_csv).reshape(test_csv.shape[0],128,-1)

In [17]:
test_D = torch.FloatTensor(test_D)

In [19]:

from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoder.fit(train_y)
train_L = encoder.transform(train_y).toarray()

In [20]:
test_L = encoder.transform(test_y).toarray()

In [21]:
train_D = torch.FloatTensor(train_D)
train_L = torch.FloatTensor(np.array(train_L))

In [22]:
import torch.utils
train_loader = torch.utils.data.DataLoader(torch.utils.data.TensorDataset(train_D, train_L), batch_size = 100, shuffle= False, drop_last = True)

#SVM

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

clf = SVC(random_state = 42, decision_function_shape='ova')
params = {
    'C' : [0.5,1,10]
}
cv = GridSearchCV(clf, param_grid = params)
cv.fit(train_csv, train_y)


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ova', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=42, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None, param_grid={'C': [0.5, 1, 10]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
pred = cv.predict(test_csv)

acc = accuracy_score(pred, test_y)
print("SVM :",acc)

SVM : 0.8982015609093994


In [ ]:
print(classification_report(pred, test_y)) #support는 정밀도의 평균? 

              precision    recall  f1-score   support

           1       0.96      0.91      0.94       520
           2       0.92      0.90      0.91       480
           3       0.89      0.90      0.89       418
           4       0.77      0.84      0.80       452
           5       0.84      0.83      0.84       540
           6       1.00      1.00      1.00       537

    accuracy                           0.90      2947
   macro avg       0.90      0.90      0.90      2947
weighted avg       0.90      0.90      0.90      2947



#CNN

In [ ]:
class CNN(torch.nn.Module):
    def __init__(self, input_size, output_size):
        super(CNN, self).__init__()
# filter 수 늘리는게 중요? kernel size 크게,

        self.layer1 = torch.nn.Sequential(torch.nn.Conv1d(input_size ,128, kernel_size= 5, stride= 1), torch.nn.MaxPool1d(kernel_size= 1), 
                                          torch.nn.ReLU()) #
        self.layer2 = torch.nn.Sequential(torch.nn.Conv1d(128,64, kernel_size= 3, stride= 1, padding =0),
                                          torch.nn.MaxPool1d(kernel_size= 1, stride = 1, padding = 0), 
                                          torch.nn.ReLU())
        self.f1 = torch.nn.Flatten()
        self.layer3 = torch.nn.Linear(192 , output_size, bias = True) #(input_size - kernel_size + 2*padding_size)/stride + 1
        #self.tanh = torch.nn.Tanh()
        torch.nn.init.kaiming_uniform(self.layer3.weight)

    def forward(self, x):
        out = self.layer1(x)
        #print(out.shape)
        out = self.layer2(out)
        #print(out.shape)
        out = self.layer3(out)
        #print(out.shape)
        out = out.view(out.size(0), -1)
        #print(out.shape)
        out = self.layer3(out)
        return out


In [ ]:
model = CNN(train_D.shape[1], train_L.shape[1]).to(device)
criterion = torch.nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 1e-3)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:14: UserWarning: nn.init.kaiming_uniform is now deprecated in favor of nn.init.kaiming_uniform_.
  


In [ ]:
running_loss =0
for e in range(1001):
  for i , data in enumerate(train_loader):
    x, y = data
    #print(x.shape)
    x = x.to(device)
    y = y.to(device)
    optimizer.zero_grad()
    h = model(x)
    loss = criterion(h, y)
    loss.backward()
    optimizer.step()
    running_loss += loss.item()
  if (e+1) % 100 == 0:
    print('[%d] loss : %.3f' %(e, running_loss / 100))
    running_loss =0

print('fin')

RuntimeError: ignored

In [ ]:
with torch.no_grad():
  model.eval()
  pred=  model(test_D.to(device))


In [ ]:
train_L

In [ ]:
test_y.shape

In [ ]:
np.array(pred).shape

In [ ]:
acc = [np.argmax(pred_lstm.cpu()[i])== np.argmax(test_L[i]) for i in range(len(test_D))]
acc = np.array(acc, dtype=np.float32)
real_acc = acc.mean()
print('CNN : ', real_acc)

CNN :  0.7960638


In [ ]:
print(classification_report(np.round(pred.cpu()), np.array(test_y)))

#LSTM

In [ ]:
train_D[0][0]

In [ ]:
#step size : 128
#input = (batch_size, time_steps, input_size)
#rnn( input_size, hidden_size)

In [ ]:
class LSTM(torch.nn.Module):
  def __init__(self, n_class, bi):
    super(LSTM, self).__init__()

    self.lstm = torch.nn.LSTM(9, 32)
    #self.lstm2 = torch.nn.LSTM(32, 32)
    self.l1 = torch.nn.Linear(128*32, n_class)
    self.dropout = torch.nn.Dropout(0.1)
    self.tanh = torch.nn.Tanh()
    self.softmax = torch.nn.Softmax(dim = 1)

  def forward(self, x):
    #print(x.shape)
    #x = x.permute(1,0,2)# 축 바꾸기. 전치행렬처럼
    #print(x.shape)
    out, hidden = self.lstm(x)
    #out, _  = self.lstm2(out, hidden)
    #out, _ = self.lstm2(out, hidden)
    #print(out.shape)
    out = self.tanh(out)
    out = self.dropout(out)
    out = out.contiguous().view(-1, 128*32)
    #print(out.shape)
    out = self.l1(out)
    #out = self.softmax(out)
    return out
#소프트맥스 지말고 탄젠트나써라

In [ ]:
model = LSTM(train_L.shape[1], False).to(device)

In [ ]:
train_L.shape[1]

6

In [ ]:
criterion = torch.nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 1e-3)

In [ ]:
running_loss =0
for e in range(201):
  for i , data in enumerate(train_loader):
    x, y = data
    x = x.to(device)
    y = y.to(device)
    optimizer.zero_grad()
    h = model(x)
    loss = criterion(h, y)
    loss.backward()
    optimizer.step()
    running_loss += loss.item()
  if e % 10 == 0:
    print('[%d] loss : %.3f' %(e, running_loss / 100))
    running_loss =0

print('fin')

[0] loss : 0.078
[10] loss : 0.424
[20] loss : 0.231
[30] loss : 0.177
[40] loss : 0.163
[50] loss : 0.137
[60] loss : 0.129
[70] loss : 0.117
[80] loss : 0.113
[90] loss : 0.112
[100] loss : 0.103
[110] loss : 0.102
[120] loss : 0.097
[130] loss : 0.094
[140] loss : 0.093
[150] loss : 0.086
[160] loss : 0.086
[170] loss : 0.084
[180] loss : 0.080
[190] loss : 0.079
[200] loss : 0.078
fin


In [ ]:
test_D.shape

In [ ]:
with torch.no_grad():
  model.eval()
  pred_lstm = model(test_D.to(device))


In [ ]:
pred_lstm.shape

In [ ]:
train_L.shape

In [ ]:
acc = [np.argmax(pred_lstm.cpu()[i])== np.argmax(test_L[i]) for i in range(len(test_D))]
acc = np.array(acc, dtype=np.float32)
real_acc = acc.mean()
print('LSTM : ', real_acc)

LSTM :  0.9290804


In [ ]:
#print(classification_report(np.round(pred_lstm.cpu()), np.array(test_y)))

#CNN + SVM

In [ ]:
class CNN(torch.nn.Module):
    def __init__(self, input_size, output_size):
        super(CNN, self).__init__()
# filter 수 늘리는게 중요? kernel size 크게,

        self.layer1 = torch.nn.Sequential(torch.nn.Conv1d(input_size ,128, kernel_size= 5, stride= 1), torch.nn.MaxPool1d(kernel_size= 1), 
                                          torch.nn.ReLU()) #
        self.layer2 = torch.nn.Sequential(torch.nn.Conv1d(128,64, kernel_size= 3, stride= 1, padding =0),
                                          torch.nn.MaxPool1d(kernel_size= 1, stride = 1, padding = 0), 
                                          torch.nn.ReLU())
        self.f1 = torch.nn.Flatten()
        self.layer3 = torch.nn.Linear(192 , output_size, bias = True) #(input_size - kernel_size + 2*padding_size)/stride + 1
        #self.tanh = torch.nn.Tanh()
        self.softmax = torch.nn.Softmax()
        torch.nn.init.kaiming_uniform(self.layer3.weight)

    def forward(self, x):
        out = self.layer1(x)
        #print(out.shape)
        out = self.layer2(out)
        #print(out.shape)
        out = out.view(out.size(0), -1)
        out = self.f1(out)
        #print(out.shape)
        model = self.layer3(out)
        model = self.tanh(model)
        #model = self.tanh(model)
        return out, model

In [ ]:
model = CNN(train_D.shape[1], train_L.shape[1]).to(device)
criterion = torch.nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 1e-3)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:14: UserWarning: nn.init.kaiming_uniform is now deprecated in favor of nn.init.kaiming_uniform_.
  


In [ ]:
running_loss = 0
new_train = []
epoch =1001
for e in range(epoch + 1):
  for i , data in enumerate(train_loader):
    x, y = data
    #print(x.shape)
    x = x.to(device)
    y = y.to(device)
    optimizer.zero_grad()
    new_x, h = model(x)
    loss = criterion(h, y)
    loss.backward()
    optimizer.step()
    running_loss += loss.item()
    if e == epoch:
        new_train.extend(new_x.cpu().detach().numpy())

  if (e+1) % 100 == 0:
    print('[%d] loss : %.3f' %(e, running_loss / 100))
    running_loss =0
  

print('fin')

[99] loss : 0.273
[199] loss : 0.210
[299] loss : 0.180
[399] loss : 0.151
[499] loss : 0.121
[599] loss : 0.126
[699] loss : 0.103
[799] loss : 0.089
[899] loss : 0.087
[999] loss : 0.074
fin


In [ ]:
train_D.shape

In [ ]:
np.array(new_train).shape

In [ ]:
train_y.shape

In [ ]:
test_csv.shape

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

clf = SVC(random_state = 42, C = 0.5, kernel = 'linear')
params = {
    #'decision_function_shape' : [ 'ovr', 'ova'],
    #'C' : [0.5,1,10], 'kernel':['rbf','linear']
}
cv = GridSearchCV(clf, param_grid = params)
cv.fit(np.array(new_train), train_y[:-52])



/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=0.5, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='linear', max_iter=-1,
                           probability=False, random_state=42, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None, param_grid={},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
cv.best_params_# 0.5, ovr, linear

{}

In [ ]:
with torch.no_grad():
  model.eval()
  new_test, _=  model(test_D.to(device))

In [ ]:
new_test.shape

torch.Size([2947, 192])

In [ ]:
for_test = new_test.cpu()#np.resize(new_test.cpu(), (2947, 64*3))

In [ ]:
pred = cv.predict(for_test)#(new_test.cpu().reshape(2947, 128*3))

In [ ]:
np.array(pred).shape

(2947,)

In [ ]:
test_y.shape

(2947, 1)

In [ ]:
print(classification_report(pred, test_y))

              precision    recall  f1-score   support

           1       0.96      0.85      0.90       557
           2       0.89      0.94      0.91       444
           3       0.92      0.95      0.94       405
           4       0.75      0.79      0.77       465
           5       0.83      0.82      0.82       539
           6       1.00      1.00      1.00       537

    accuracy                           0.89      2947
   macro avg       0.89      0.89      0.89      2947
weighted avg       0.89      0.89      0.89      2947



In [ ]:
acc = accuracy_score(pred, test_y)
print("CNN_SVM :",acc)

CNN_SVM : 0.8903970139124533


#LSTM + SVM

In [ ]:
class LSTM(torch.nn.Module):
  def __init__(self, n_class, bi):
    super(LSTM, self).__init__()

    self.lstm = torch.nn.LSTM(9, 32)
    #self.lstm2 = torch.nn.LSTM(32, 32)
    self.l1 = torch.nn.Linear(128*32, n_class)
    self.dropout = torch.nn.Dropout(0.1)
    self.tanh = torch.nn.Tanh()
    self.softmax = torch.nn.Softmax(dim = 1)

  def forward(self, x):
    #print(x.shape)
    #x = x.permute(1,0,2)# 축 바꾸기. 전치행렬처럼
    #print(x.shape)
    out, hidden = self.lstm(x)
    #out, _  = self.lstm2(out, hidden)
    #print(out.shape)
    out = self.tanh(out)
    #out = self.dropout(out)
    out = out.contiguous().view(-1, 128*32)
    #print(out.shape)
    model = self.l1(out)
    #out = self.softmax(out)
    return out, model
#소프트맥스 지말고 탄젠트나써라

In [ ]:
model = LSTM(train_L.shape[1], False).to(device)

In [ ]:
criterion = torch.nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 1e-3)

In [ ]:
running_loss = 0
epoch = 200
new_train = []
for e in range(epoch+1):
  for i , data in enumerate(train_loader):
    x, y = data
    x = x.to(device)
    y = y.to(device)
    optimizer.zero_grad()
    new_t, h = model(x)
    loss = criterion(h, y)
    loss.backward()
    optimizer.step()
    running_loss  += loss.item()
    if e == epoch:
      new_train.extend(new_t.cpu().detach().numpy())
  if (e) % 10 == 0:
    print('[%d] loss : %.3f' %(e, running_loss / 100))
    running_loss = 0

print('fin')

[0] loss : 0.078
[10] loss : 0.394
[20] loss : 0.211
[30] loss : 0.161
[40] loss : 0.133
[50] loss : 0.124
[60] loss : 0.114
[70] loss : 0.108
[80] loss : 0.096
[90] loss : 0.099
[100] loss : 0.089
[110] loss : 0.087
[120] loss : 0.080
[130] loss : 0.074
[140] loss : 0.078
[150] loss : 0.073
[160] loss : 0.069
[170] loss : 0.071
[180] loss : 0.068
[190] loss : 0.066
[200] loss : 0.062
fin


In [ ]:
np.array(new_train).shape

(7300, 4096)

In [ ]:
#new_train = np.resize(new_train, (7400,))

In [ ]:
new_train

[array([ 0.01777264,  0.06048835, -0.01753551, ..., -0.04283169,
         0.04891417,  0.04133761], dtype=float32),
 array([ 0.00207993,  0.0313543 , -0.00095009, ..., -0.03336694,
         0.04389487,  0.04810051], dtype=float32),
 array([-0.00654274,  0.01649543,  0.00906717, ..., -0.02660595,
         0.04047364,  0.04541314], dtype=float32),
 array([-0.01196849,  0.0085832 ,  0.01459578, ..., -0.023973  ,
         0.04107356,  0.03982279], dtype=float32),
 array([-0.01465636,  0.00432397,  0.01668845, ..., -0.02235164,
         0.04303858,  0.03312483], dtype=float32),
 array([-0.0169461 ,  0.00208852,  0.01784271, ..., -0.02072057,
         0.04537154,  0.0259371 ], dtype=float32),
 array([-0.01811997,  0.00089237,  0.01792175, ..., -0.01787638,
         0.04674875,  0.01804803], dtype=float32),
 array([-1.8954560e-02,  6.4177955e-05,  1.8106893e-02, ...,
        -1.4892922e-02,  4.7903009e-02,  1.0539680e-02], dtype=float32),
 array([-0.01878494, -0.00055484,  0.01760163, ..., -0

In [ ]:
train_y

label
0         5
1         5
2         5
3         5
4         5
...     ...
7347      2
7348      2
7349      2
7350      2
7351      2

[7352 rows x 1 columns]

In [ ]:
PATH = './file.pt'
torch.save({
            'epoch': 200,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'loss': loss,

            }, PATH)

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

clf = SVC(random_state = 42, C = 0.5, kernel = 'linear')
params = {
    #'C' : [0.05, 0.5,1,10], 'kernel':['rbf','linear'], 'decision_function_shape':['ova','ovr']
}
cv = GridSearchCV(clf, param_grid = params)
cv.fit(np.array(new_train), np.array(train_y[:-52]))


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=0.5, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='linear', max_iter=-1,
                           probability=False, random_state=42, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None, param_grid={},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
with torch.no_grad():
  model.eval()
  new_test, _=  model(test_D.to(device))

In [ ]:
new_test = np.array(new_test.cpu())#np.resize(new_test, (2996,128))

In [ ]:
pred = cv.predict(new_test)

In [ ]:
print(classification_report(pred, test_y))

              precision    recall  f1-score   support

           1       0.99      0.97      0.98       509
           2       0.99      0.97      0.98       483
           3       0.92      0.98      0.95       397
           4       0.93      0.94      0.94       486
           5       0.94      0.94      0.94       535
           6       1.00      1.00      1.00       537

    accuracy                           0.96      2947
   macro avg       0.96      0.96      0.96      2947
weighted avg       0.96      0.96      0.96      2947



In [ ]:
acc = accuracy_score(pred, test_y)
print("LSTM_SVM :",acc)

LSTM_SVM : 0.9613165931455717


#bi-LSTM + SVM

In [ ]:
model = LSTM(train_L.shape[1], True).to(device)

In [ ]:
criterion = torch.nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 1e-3)

In [ ]:
running_loss = 0
epoch = 200
new_train = []
for e in range(epoch+1):
  for i , data in enumerate(train_loader):
    x, y = data
    x = x.to(device)
    y = y.to(device)
    optimizer.zero_grad()
    new_t, h = model(x)
    loss = criterion(h, y)
    loss.backward()
    optimizer.step()
    running_loss  += loss.item()
    if e == epoch:
      new_train.extend(new_t.cpu().detach().numpy())
  if (e) % 10 == 0:
    print('[%d] loss : %.3f' %(e, running_loss / 100))
    running_loss = 0

print('fin')

[0] loss : 0.081
[10] loss : 0.393
[20] loss : 0.205
[30] loss : 0.161
[40] loss : 0.139
[50] loss : 0.124
[60] loss : 0.112
[70] loss : 0.108
[80] loss : 0.096
[90] loss : 0.093
[100] loss : 0.087
[110] loss : 0.082
[120] loss : 0.079
[130] loss : 0.074
[140] loss : 0.074
[150] loss : 0.071
[160] loss : 0.066
[170] loss : 0.068
[180] loss : 0.063
[190] loss : 0.063
[200] loss : 0.063
fin


In [ ]:
np.array(new_train).shape

(7300, 4096)

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

clf = SVC(random_state = 42, C = 0.5, kernel = 'linear')
params = {
    #'C' : [0.05, 0.5,1,10], 'kernel':['rbf','linear'], 'decision_function_shape':['ova','ovr']
}
cv = GridSearchCV(clf, param_grid = params)
cv.fit(np.array(new_train), np.array(train_y[:-52]))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example usin

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=0.5, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='linear', max_iter=-1,
                           probability=False, random_state=42, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None, param_grid={},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
with torch.no_grad():
  model.eval()
  new_test, _=  model(test_D.to(device))

In [ ]:
new_test = np.array(new_test.cpu())

In [ ]:
pred = cv.predict(new_test)

In [ ]:
print(classification_report(pred, test_y))

              precision    recall  f1-score   support

           1       0.93      0.95      0.94       487
           2       0.90      0.93      0.92       460
           3       0.89      0.85      0.87       438
           4       0.95      0.87      0.91       535
           5       0.87      0.94      0.90       490
           6       1.00      1.00      1.00       537

    accuracy                           0.93      2947
   macro avg       0.92      0.92      0.92      2947
weighted avg       0.93      0.93      0.92      2947



In [ ]:
acc = accuracy_score(pred, test_y)
print("bi-LSTM_SVM :",acc)

bi-LSTM_SVM : 0.9250084832032576
